pipeline {

    // Execute pipeline on any available Jenkins agent
    agent any

    // Trigger pipeline automatically on GitHub push
    triggers {
        githubPush()
    }


    // Global pipeline options
    options {
            timestamps()
            disableConcurrentBuilds()
            timeout(time: 60, unit: 'MINUTES')

            // Keep this only if the AnsiColor plugin is installed
            ansiColor('xterm')
        }

    // Global environment variables
    environment {
            AWS_DEFAULT_REGION = 'us-east-1'
            PATH = "/usr/local/bin:/usr/bin:/bin:${env.PATH}"
        }

    stages {

        // Checkout source code from GitHub
        stage('Checkout Source Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/nileshgk/wordpress-project.git'
                    // credentialsId: 'github-credentials' // Required for private repositories
            }
        }

        stage('Install Required Tools') {
            steps {
                sh '''
                set -e

                export DEBIAN_FRONTEND=noninteractive

                sudo apt-get update

                sudo apt-get install -y \
                    curl \
                    unzip \
                    wget \
                    git \
                    jq \
                    gnupg \
                    software-properties-common

                # Install AWS CLI
                if ! command -v aws >/dev/null 2>&1; then
                    echo "Installing AWS CLI..."

                    cd /tmp

                    rm -rf aws awscliv2.zip

                   curl -sSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip \
                        -o awscliv2.zip

                    unzip -oq awscliv2.zip

                    sudo ./aws/install --update

                    rm -rf aws awscliv2.zip
                fi

                # Install Terraform
                if ! command -v terraform >/dev/null 2>&1; then

                    wget -qO- https://apt.releases.hashicorp.com/gpg | \
                    gpg --dearmor | \
                    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null

                    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
                    sudo tee /etc/apt/sources.list.d/hashicorp.list

                    sudo apt-get update

                    sudo apt-get install -y terraform
                fi

                # Install Docker
                if ! command -v docker >/dev/null 2>&1; then

                    sudo apt-get install -y docker.io

                    sudo systemctl enable docker

                    sudo systemctl start docker

                    sudo usermod -aG docker jenkins
                fi

                # Install Ansible
                if ! command -v ansible >/dev/null 2>&1; then
                    sudo apt-get install -y ansible
                fi

                sudo apt-get install -y python3 python3-pip
                '''
            }
        }

        // Verify all required DevOps tools are installed
        stage('Verify Build Environment') {
            steps {
                sh '''
                set -e

                echo "===== Java ====="
                java -version

                echo "===== Git ====="
                git --version

                echo "===== Terraform ====="
                terraform version

                echo "===== AWS CLI ====="
                aws --version

                echo "===== Docker ====="
                docker --version

                echo "===== Ansible ====="
                ansible --version

                echo "===== Environment Ready ====="
                '''
            }
        }   

        // Validate AWS authentication using IAM Role or configured credentials
        stage('Validate AWS Credentials') {
            steps {
                sh '''
                set -e

                echo "Validating AWS Credentials..."

                if aws sts get-caller-identity >/dev/null 2>&1
                then
                    echo "AWS Authentication Successful"

                    aws sts get-caller-identity
                else
                    echo ""
                    echo "ERROR: AWS Credentials not found."
                    echo "Attach an IAM Role to Jenkins EC2"
                    echo "or configure Jenkins AWS Credentials."
                    exit 1
                fi
                '''
            }
        }

        // Display Jenkins workspace structure (Debug stage)
        stage('Debug Workspace') {
            steps {
                sh '''
                pwd

                echo "===== Workspace ====="
                ls -R
                '''
            }
        }

        // Display Terraform directory contents (Debug stage)
        stage('Debug Terraform') {
            steps {
                dir('wordpress-devops/terraform') {
                    sh '''
                    echo "Current Directory:"
                    pwd

                    echo "Files:"
                    ls -lah

                    echo "Terraform Files:"
                    find . -name "*.tf"

                    echo "Terraform Version:"
                    terraform version
                    '''
                }
            }
        }

        // Check Terraform code formatting
        stage('Terraform Format') {
            steps {
                dir('wordpress-devops/terraform') {
                    sh 'terraform fmt -recursive -check'
                }
            }
        }

        // Initialize Terraform providers and backend
        stage('Terraform Init') {
            steps {
                dir('wordpress-devops/terraform') {
                    sh '''
                    terraform init \
                        -reconfigure \
                        -input=false
                    '''
                }
            }
        }

        // Validate Terraform configuration
        stage('Terraform Validate') {
            steps {
                dir('wordpress-devops/terraform') {
                    sh 'terraform validate'
                }
            }
        }

        // Generate Terraform execution plan
        stage('Terraform Plan') {
            steps {
                dir("${WORKSPACE}/wordpress-devops/terraform") {
                    sh '''
                    echo "===== WORKSPACE ====="
                    echo $WORKSPACE

                    echo "===== CURRENT DIRECTORY ====="
                    pwd

                    echo "===== FILES ====="
                    ls -lah

                    echo "===== TERRAFORM FILES ====="
                    find . -maxdepth 1 -name "*.tf"

                    terraform plan \
                        -input=false \
                        -out=tfplan
                    '''
                }
            }
        }

        // Create AWS infrastructure
        stage('Terraform Apply') {
            steps {
                dir('wordpress-devops/terraform') {
                    sh '''
                    terraform apply \
                        -input=false \
                        -auto-approve \
                        tfplan
                    '''
                }
            }
        }

        // Display Terraform outputs (Public IP, etc.)
        stage('Terraform Output') {
            steps {
                dir('wordpress-devops/terraform') {
                    sh 'terraform output'
                }
            }
        }

        // Wait for EC2 instance to finish initialization
        stage('Wait For EC2') {
            steps {
                echo "Waiting for EC2 initialization..."
                sleep(time: 60, unit: 'SECONDS')
            }
        }

        // Generate dynamic Ansible inventory from Terraform output
        stage('Generate Inventory') {
            steps {
                dir('wordpress-devops') {
                    sh 'chmod +x scripts/generate_inventory.sh'
                    sh './scripts/generate_inventory.sh'
                }
            }
        }

        // Verify generated inventory file
        stage('Verify Inventory') {
            steps {
                dir('wordpress-devops') {
                    sh '''
                    echo "Generated Inventory:"
                    cat ansible/inventory
                    '''
                }
            }
        }

        // Test SSH connectivity to EC2
        stage('Ping EC2') {
            steps {
                dir('wordpress-devops/ansible') {
                    sh '''
                    ansible wordpress \
                    -m ping \
                    -v
                    '''
                }
            }
        }

        // Install required Ansible Galaxy collection
        stage('Install Ansible Collection') {
            steps {
                sh '''
                ansible-galaxy collection install community.docker --force
                '''
            }
        }

        // Deploy Dockerized WordPress and MySQL using Ansible
        stage('Deploy WordPress') {
            steps {

                withCredentials([
                    string(credentialsId: 'mysql-password', variable: 'MYSQL_PASSWORD'),
                    string(credentialsId: 'mysql-root-password', variable: 'MYSQL_ROOT_PASSWORD')
                ]) {

                    dir('wordpress-devops/ansible') {

                        sh '''
                        ansible-playbook playbook.yml \
                        -e mysql_password=$MYSQL_PASSWORD \
                        -e mysql_root_password=$MYSQL_ROOT_PASSWORD \
                        -v
                        '''

                    }

                }

            }
        }

        // Verify Docker containers are running
        stage('Verify Containers') {
            steps {
                dir('wordpress-devops/ansible') {
                    sh '''
                    ansible wordpress \
                    -a "docker ps"
                    '''
                }
            }
        }

        // Perform application health check
        stage('Application Health Check') {
            steps {

                script {

                    def PUBLIC_IP = sh(
                        script: "terraform -chdir=wordpress-devops/terraform output -raw public_ip",
                        returnStdout: true
                    ).trim()

                    sh """
                    echo "Checking WordPress..."

                    curl --retry 10 \
                         --retry-delay 5 \
                         http://${PUBLIC_IP}:8080
                    """

                }

            }
        }

    }

    // Execute after pipeline completion
    post {

        // Executed when all stages succeed
        success {

            echo '''
=========================================
 WordPress Deployment Successful
=========================================
'''

        }

        // Executed when any stage fails
        failure {

            echo '''
=========================================
 WordPress Deployment Failed
 Check Jenkins Console Output
=========================================
'''

        }

        // Always clean workspace after execution
        always {

            cleanWs()

        }

    }

}