---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Install Python Docker SDK
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Install Docker Compose plugin
  ansible.builtin.apt:
    name: docker-compose-v2
    state: present
  ignore_errors: true

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes