---

- name: Create Application Directory
  file:
    path: /opt/wordpress
    state: directory
    mode: "0755"

- name: Copy Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: /opt/wordpress/docker-compose.yml
    mode: "0644"
  notify: Restart WordPress

- name: Start WordPress
  community.docker.docker_compose_v2:
    project_src: /opt/wordpress
    state: present